### ISSUE TITLE
fails if the notification daemon restarts/changes

### ISSUE THREAD

**Issue by dario23** [wavexx/networkd-notify#2]
the notification daemon dbus address is only looked up once at the start; so if it ever changes (e.g. because the notification daemon restarts) networkd-notify will print the following error message:

```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/dario/git/networkd-notify/networkd-notify", line 127, in property_changed
    continue
  File "/home/dario/git/networkd-notify/networkd-notify", line 35, in notify
    NOTIFY_IF = dbus.Interface(bus.get_object('org.freedesktop.Notifications',
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.9 was not provided by any .service files
```

probably the easiest fix would be to move the dbus user-session client lookup into `notify` and do it each time a message gets sent; but for avoiding a little overhead it might also be done only on exceptions when sending (or something along those lines)

**Comment by wavexx** [comment]
Uhm, both ugly solutions. Isn't there an event for service registration we can use maybe?

Similarly, the interface name map is never updated. Since there's no event from networkd, one would need to fetch the device state at each notification, which is something I intentionally avoided.

**Comment by dario23** [comment]
there seems to be a `NameOwnerChanged` dbus signal (where "signal" seems to be dbus-speak for stuff that is broadcast to anyone willing to listen), so we could listen for that; i don't really know that much dbus though, so i'll have to put some time into it (or you'd say you know that stuff anyways and it's a matter of some minutes for you)

**Comment by dario23** [comment]
so i wrote some code that seems to do what i wanted, please take a look :-)
