### ISSUE TITLE
Handle interface changes correctly

### ISSUE THREAD

**Issue by wavexx** [wavexx/networkd-notify#4]
If an interface is added/removed, IFACE_MAP is not updated, causing either a crash or bogus info to be reported. Calling ``networkctl`` at each notification sounds bad (although we don't do much better currently).

Maybe we should parse networkd state files directly from ``/run/systemd/netif``. There's no interface yet, so there's no point in trying to be nice.

**Comment by dario23** [comment]
i looked in that direction as well, in dbus-monitor there are signals for systemd device events

`signal time=1527426485.611023 sender=:1.216 -> destination=(null destination) serial=8348 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "sys-subsystem-net-devices-enp0s20f0u1.device"
   object path "/org/freedesktop/systemd1/unit/sys_2dsubsystem_2dnet_2ddevices_2denp0s20f0u1_2edevice"`

so as a first step you could listen for those events and update the interface map when one of those happens, or even try to extract the information directly from the event (not sure where the index is in there, though).

**Comment by wavexx** [comment]
See #8
